const express=require('express');const http=require('http');const path=require('path');const {WebSocketServer}=require('ws');const crypto=require('crypto');
const app=express(),server=http.createServer(app),wss=new WebSocketServer({server}),PORT=process.env.PORT||3000;app.use(express.static(path.join(__dirname,'public')));app.get('/health',(_req,res)=>res.json({ok:true,players:players.size}));
const WORLD={half:57,maxY:8},SCORE_LIMIT=25,MATCH_MS=10*60*1000,BOT_COUNT=6,players=new Map();let matchStartedAt=Date.now();
const WEAPONS={ar:{damage:26,head:1.55,rate:105,range:90},smg:{damage:20,head:1.45,rate:72,range:52},shotgun:{damage:68,head:1.2,rate:620,range:24},dmr:{damage:44,head:1.7,rate:280,range:120},sniper:{damage:78,head:1.5,rate:980,range:160}};
// All spawns are intentionally in open streets, not inside geometry.
const spawnPoints=[[-54,1.72,0],[54,1.72,0],[0,1.72,-54],[0,1.72,54],[-29,1.72,-28],[29,1.72,-28],[-29,1.72,28],[29,1.72,28],[-15,1.72,0],[15,1.72,0],[0,1.72,-15],[0,1.72,15],[-31,1.72,0],[31,1.72,0],[0,1.72,-31],[0,1.72,31]];
function randName(){const a=['Nova','Ghost','Viper','Rook','Echo','Neon','Zero','Kite','Atlas','Flux'];return a[Math.floor(Math.random()*a.length)]+Math.floor(100+Math.random()*900)}function clamp(n,min,max){return Math.max(min,Math.min(max,n))}function sanitizeName(v){return String(v||randName()).replace(/[^a-zA-Z0-9 _-]/g,'').trim().slice(0,18)||randName()}
function safeSpawn(exceptId){let best=spawnPoints[Math.floor(Math.random()*spawnPoints.length)],bestDist=-1;for(const s of spawnPoints){let nearest=Infinity;for(const p of players.values()){if(!p.alive||p.id===exceptId)continue;nearest=Math.min(nearest,Math.hypot(s[0]-p.x,s[2]-p.z))}if(nearest>bestDist){bestDist=nearest;best=s}}return best}
function resetPlayer(p,keepScore=true){const s=safeSpawn(p.id);p.x=s[0];p.y=s[1];p.z=s[2];p.yaw=0;p.pitch=0;p.hp=100;p.alive=true;p.respawnAt=0;if(!keepScore){p.score=0;p.kills=0;p.deaths=0;p.streak=0}}
function snapshot(){return{type:'snapshot',now:Date.now(),matchEndsAt:matchStartedAt+MATCH_MS,scoreLimit:SCORE_LIMIT,players:[...players.values()].map(p=>({id:p.id,name:p.name,x:p.x,y:p.y,z:p.z,yaw:p.yaw,pitch:p.pitch,hp:p.hp,alive:p.alive,score:p.score,kills:p.kills,deaths:p.deaths,streak:p.streak,respawnAt:p.respawnAt,isBot:!!p.isBot,weapon:p.weapon}))}}function broadcast(obj){const data=JSON.stringify(obj);for(const ws of wss.clients)if(ws.readyState===1)ws.send(data)}
function makeBot(i){const id=`bot-${i}-${crypto.randomBytes(3).toString('hex')}`,names=['Cipher','Razor','Volt','Nyx','Kestrel','Mako','Drift'];const p={id,name:names[i%names.length]+'-AI',x:0,y:1.72,z:0,yaw:0,pitch:0,hp:100,alive:true,score:0,kills:0,deaths:0,streak:0,respawnAt:0,lastShotAt:0,isBot:true,botTurn:Math.random()*Math.PI*2,weapon:['ar','smg','dmr'][i%3]};players.set(id,p);resetPlayer(p,true)}
function damageTarget(attacker,target,damage,headshot=false){if(!attacker?.alive||!target?.alive||attacker.id===target.id)return;target.hp-=damage;broadcast({type:'hit',shooter:attacker.id,target:target.id,damage,hp:Math.max(0,target.hp)});if(target.hp<=0){target.alive=false;target.hp=0;target.deaths++;target.streak=0;target.respawnAt=Date.now()+2200;attacker.kills++;attacker.streak++;attacker.score+=headshot?125:100;broadcast({type:'kill',killer:attacker.id,victim:target.id,killerName:attacker.name,victimName:target.name,headshot,streak:attacker.streak});endMatchIfNeeded()}}
for(let i=0;i<BOT_COUNT;i++)makeBot(i);
function endMatchIfNeeded(){const winner=[...players.values()].sort((a,b)=>b.score-a.score)[0];if((winner&&winner.score>=SCORE_LIMIT)||Date.now()-matchStartedAt>=MATCH_MS){broadcast({type:'matchEnd',winner:winner?{id:winner.id,name:winner.name,score:winner.score}:null});matchStartedAt=Date.now();for(const p of players.values())resetPlayer(p,false)}}
wss.on('connection',ws=>{const id=crypto.randomUUID(),p={id,name:randName(),x:0,y:1.72,z:0,yaw:0,pitch:0,hp:100,alive:true,score:0,kills:0,deaths:0,streak:0,respawnAt:0,lastShotAt:0,weapon:'ar'};players.set(id,p);resetPlayer(p,true);ws.playerId=id;ws.send(JSON.stringify({type:'welcome',id,scoreLimit:SCORE_LIMIT}));broadcast({type:'feed',text:`${p.name} entered the storm.`});ws.on('message',raw=>{let msg;try{msg=JSON.parse(String(raw))}catch{return}const me=players.get(id);if(!me)return;if(msg.type==='hello'){me.name=sanitizeName(msg.name);if(WEAPONS[msg.weapon])me.weapon=msg.weapon;return}if(msg.type==='weapon'&&WEAPONS[msg.weapon]){me.weapon=msg.weapon;return}if(msg.type==='move'&&me.alive){const x=Number(msg.x),y=Number(msg.y),z=Number(msg.z);if(![x,y,z].every(Number.isFinite))return;me.x=clamp(x,-WORLD.half,WORLD.half);me.y=clamp(y,1,WORLD.maxY);me.z=clamp(z,-WORLD.half,WORLD.half);me.yaw=Number.isFinite(msg.yaw)?msg.yaw:me.yaw;me.pitch=Number.isFinite(msg.pitch)?clamp(msg.pitch,-1.5,1.5):me.pitch;return}if(msg.type==='shoot'&&me.alive){const w=WEAPONS[msg.weapon]||WEAPONS[me.weapon];if(!w)return;const now=Date.now();if(now-me.lastShotAt<w.rate*.85)return;me.lastShotAt=now;me.weapon=WEAPONS[msg.weapon]?msg.weapon:me.weapon;const target=players.get(String(msg.targetId||''));if(!target||!target.alive||target.id===me.id)return;const dist=Math.hypot(me.x-target.x,me.y-target.y,me.z-target.z);if(dist>w.range+3)return;const damage=Math.round(w.damage*(msg.headshot?w.head:1));damageTarget(me,target,damage,!!msg.headshot)}});ws.on('close',()=>{const old=players.get(id);players.delete(id);if(old)broadcast({type:'feed',text:`${old.name} disconnected.`})})});
setInterval(()=>{const now=Date.now();for(const p of players.values())if(!p.alive&&p.respawnAt&&now>=p.respawnAt)resetPlayer(p,true);for(const bot of players.values()){if(!bot.isBot||!bot.alive)continue;const targets=[...players.values()].filter(p=>p.alive&&p.id!==bot.id);if(!targets.length)continue;targets.sort((a,b)=>Math.hypot(bot.x-a.x,bot.z-a.z)-Math.hypot(bot.x-b.x,bot.z-b.z));const target=targets[0],dx=target.x-bot.x,dz=target.z-bot.z,dist=Math.max(.001,Math.hypot(dx,dz));bot.yaw=Math.atan2(-dx,-dz);bot.botTurn+=(Math.random()-.5)*.03;const strafe=Math.sin(now/650+bot.botTurn)*.07;if(dist>6){const speed=.12;bot.x=clamp(bot.x+dx/dist*speed+dz/dist*strafe,-WORLD.half,WORLD.half);bot.z=clamp(bot.z+dz/dist*speed-dx/dist*strafe,-WORLD.half,WORLD.half)}if(dist<34&&now-bot.lastShotAt>420+Math.random()*600){bot.lastShotAt=now;const accuracy=Math.max(.2,.8-dist/55);if(Math.random()<accuracy)damageTarget(bot,target,12+Math.floor(Math.random()*12),Math.random()<.07)}}endMatchIfNeeded();broadcast(snapshot())},50);
server.listen(PORT,'0.0.0.0',()=>console.log(`Neon Storm FFA listening on ${PORT}`));
